/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 test.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/test.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base.geometry} material={materials.Base} position={[-2.04, 0.14, -0.88]} />
      <mesh geometry={nodes.Window_glass.geometry} material={materials['Window glass']} position={[3.37, 1.83, 4.87]} rotation={[Math.PI, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Balustrade.geometry} material={materials.Balustrade} position={[4.88, -1.35, 6.84]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Walls_inside.geometry} material={materials['Wall plaster']} position={[-0.81, 2.08, -1.89]} />
      <group position={[0, 0, 9.42]}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials.Copper} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials['White window']} />
      </group>
      <group position={[0, 1.7, 0]} scale={[1.58, 1, 1.58]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Ceiling} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Base} />
      </group>
      <mesh geometry={nodes.Window_sill.geometry} material={materials['Marble 01']} position={[0, 1.5, 0]} scale={[1.58, 1, 1.58]} />
      <mesh geometry={nodes.Door_frame.geometry} material={materials.White_Door} position={[-1.48, 1.23, 2.14]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Handle.geometry} material={materials.Copper} position={[3.25, 1.14, 4.92]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[0, 0, 4.9]}>
        <mesh geometry={nodes.Mesh019.geometry} material={materials.Copper} />
        <mesh geometry={nodes.Mesh019_1.geometry} material={materials['White window']} />
      </group>
      <group position={[-6.06, 1.37, 0.05]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Untitled005.geometry} material={materials.Copper} />
        <mesh geometry={nodes.Untitled005_1.geometry} material={materials.White_Door} />
      </group>
      <group position={[-3.98, 1.37, 6.14]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Untitled006.geometry} material={materials.Copper} />
        <mesh geometry={nodes.Untitled006_1.geometry} material={materials.White_Door} />
      </group>
      <mesh geometry={nodes.Ceiling_top.geometry} material={materials['White plane']} position={[0, 1.5, 0]} scale={[1.58, 1, 1.58]} />
      <mesh geometry={nodes.Shelfs.geometry} material={materials.Base} />
      <mesh geometry={nodes.Shelf.geometry} material={materials['Marble 01']} />
      <mesh geometry={nodes.Walls_outside.geometry} material={materials['White plane']} position={[0, 1.5, 0]} scale={[1.58, 1, 1.58]} />
      <mesh geometry={nodes.Cabinet.geometry} material={materials.Wood} position={[-2.76, 0, 6.83]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Table.geometry} material={materials.Table} position={[-0.94, 0, 4.83]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[1.44, 0, 1.3]} rotation={[Math.PI / 2, 0, 0.07]} scale={0.01}>
        <mesh geometry={nodes.ZU_OMG_Chair010.geometry} material={materials['Black legs']} />
        <mesh geometry={nodes.ZU_OMG_Chair010_1.geometry} material={materials['Chair fabric 02']} />
      </group>
      <mesh geometry={nodes.Drawer.geometry} material={materials.Wood} position={[-4.26, 0.39, 1.72]} rotation={[0, 1.57, 0]} scale={[1.39, 1, 1.39]} />
      <group position={[-4.05, 0.35, -2.56]} rotation={[0, 0.01, 0]}>
        <mesh geometry={nodes.ASTON_ARMCHAIR_CM74_001.geometry} material={materials['Armchair fabric 02']} />
        <mesh geometry={nodes.ASTON_ARMCHAIR_CM74_001_1.geometry} material={materials['Black legs']} />
      </group>
      <group position={[-2.44, 0.35, -2.57]} rotation={[0, 0.64, 0]}>
        <mesh geometry={nodes.ASTON_ARMCHAIR_CM74_001.geometry} material={materials['Armchair fabric 02']} />
        <mesh geometry={nodes.ASTON_ARMCHAIR_CM74_001_1.geometry} material={materials['Black legs']} />
      </group>
      <group position={[1.73, 0.44, -5.51]} rotation={[0, -Math.PI / 3, 0]}>
        <mesh geometry={nodes['LESLIE_BERG�RE_CM68_027'].geometry} material={materials['Armchair back']} />
        <mesh geometry={nodes['LESLIE_BERG�RE_CM68_027_1'].geometry} material={materials['Armchair fabric 01']} />
        <mesh geometry={nodes['LESLIE_BERG�RE_CM68_027_2'].geometry} material={materials['Black legs']} />
      </group>
      <group position={[-3.39, 0.02, -3.68]}>
        <mesh geometry={nodes.Ligne_Roset_Liam_Low_Table.geometry} material={materials.Copper} />
        <mesh geometry={nodes.Ligne_Roset_Liam_Low_Table_1.geometry} material={materials['Glass table']} />
        <mesh geometry={nodes.Ligne_Roset_Liam_Low_Table_2.geometry} material={materials['Glass table edge']} />
      </group>
      <group position={[-3.83, 0.38, -5.09]} rotation={[0, 0.43, 0]}>
        <mesh geometry={nodes._SEYMOUR_SEMI_ROUND_SOFA_MIX_CM_315_045002.geometry} material={materials['Sofa fabric']} />
        <mesh geometry={nodes._SEYMOUR_SEMI_ROUND_SOFA_MIX_CM_315_045002_1.geometry} material={materials['Sofa legs']} />
        <mesh geometry={nodes._SEYMOUR_SEMI_ROUND_SOFA_MIX_CM_315_045002_2.geometry} material={materials['Sofa pillows']} />
      </group>
      <mesh geometry={nodes.Desk.geometry} material={materials.Wood} position={[1.37, 0, 1.84]} />
      <mesh geometry={nodes.Pot.geometry} material={materials.Clay} />
      <mesh geometry={nodes.Painting_02.geometry} material={materials['Painting 02']} />
      <group position={[-3.84, 1.61, 2.08]} rotation={[-Math.PI / 2, 0, 0]} scale={0.4}>
        <mesh geometry={nodes.frame_IKEA003.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA003_1.geometry} material={materials.Picture_02} />
        <mesh geometry={nodes.frame_IKEA003_2.geometry} material={materials['passe-partout']} />
      </group>
      <group position={[-4.47, 1.93, 2.07]} rotation={[-Math.PI / 2, 0, 0]} scale={0.76}>
        <mesh geometry={nodes.frame_IKEA004.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA004_1.geometry} material={materials.Picture_02} />
        <mesh geometry={nodes.frame_IKEA004_2.geometry} material={materials['passe-partout']} />
      </group>
      <group position={[-3.82, 2.08, 2.08]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.57}>
        <mesh geometry={nodes.frame_IKEA005.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA005_1.geometry} material={materials.Picture_04} />
        <mesh geometry={nodes.frame_IKEA005_2.geometry} material={materials['passe-partout']} />
      </group>
      <group position={[-3.84, 1.21, 2.08]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.4}>
        <mesh geometry={nodes.frame_IKEA006.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA006_1.geometry} material={materials.Picture_03} />
        <mesh geometry={nodes.frame_IKEA006_2.geometry} material={materials['passe-partout']} />
      </group>
      <mesh geometry={nodes.Painting_03.geometry} material={materials['Painting 03']} />
      <mesh geometry={nodes.Painting_01.geometry} material={materials['Painting 01']} />
      <group position={[-1.02, 1.96, 4.83]}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials['Lamp black']} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials['Lamp white']} />
        <mesh geometry={nodes.Mesh004_2.geometry} material={materials['Lamp light table']} />
      </group>
      <group position={[0.91, 0, -6.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.ZU_Tripod.geometry} material={materials['White lamp']} />
        <mesh geometry={nodes.ZU_Tripod_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.ZU_Tripod_2.geometry} material={materials['Lamp light']} />
        <mesh geometry={nodes.ZU_Tripod_3.geometry} material={materials['Metal Lamp']} />
      </group>
      <group position={[-3.15, 2.28, -3.94]} rotation={[0, 0.61, 0]} scale={0}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['Lamp light']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Lamp black']} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials['Lamp glass']} />
      </group>
      <group position={[1.81, 0.74, 1.85]}>
        <mesh geometry={nodes.Tip_Table_Lamp.geometry} material={materials.Lamp_01} />
        <mesh geometry={nodes.Tip_Table_Lamp_1.geometry} material={materials['Lamp light']} />
      </group>
      <mesh geometry={nodes.Vase.geometry} material={materials['Marble 02']} position={[-1.17, 0.84, -6.54]} />
      <group position={[-4.76, 0.75, 1.8]} rotation={[Math.PI, 0, Math.PI]} scale={0.79}>
        <mesh geometry={nodes.candle_1.geometry} material={materials['Marble 01']} />
        <mesh geometry={nodes.candle_2.geometry} material={materials['Candle wick']} />
        <mesh geometry={nodes.candle_3.geometry} material={materials.Candle} />
      </group>
      <group position={[-3.66, 0.64, 1.85]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Ligne_Roset_Lithos_book_set.geometry} material={materials['Book pages']} />
        <mesh geometry={nodes.Ligne_Roset_Lithos_book_set_1.geometry} material={materials['Book cover 01']} />
        <mesh geometry={nodes.Ligne_Roset_Lithos_book_set_2.geometry} material={materials['Book cover 02']} />
      </group>
      <mesh geometry={nodes.Book_stand.geometry} material={materials['Marble 02']} position={[-3.66, 0.64, 1.85]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Carpet.geometry} material={materials.Rug} />
      <group position={[-3.36, 0.41, -3.58]}>
        <mesh geometry={nodes.Serax_Copper_Glass_Set.geometry} material={materials['Glass set']} />
        <mesh geometry={nodes.Serax_Copper_Glass_Set_1.geometry} material={materials.Copper} />
      </group>
      <mesh geometry={nodes.Mesh010.geometry} material={materials.Copper} />
      <mesh geometry={nodes.Mesh010_1.geometry} material={materials['White window']} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Cube008_1.geometry} material={materials['Balcony floor']} />
      <mesh geometry={nodes.Nimbus_Rectangular.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Nimbus_Rectangular_1.geometry} material={materials.Copper} />
      <mesh geometry={nodes.ZU_OMG_Chair004.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair004_1.geometry} material={materials['Chair fabric 01']} />
      <mesh geometry={nodes.ZU_OMG_Chair002.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair002_1.geometry} material={materials['Chair fabric 02']} />
      <mesh geometry={nodes.ZU_OMG_Chair003.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair003_1.geometry} material={materials['Chair fabric 01']} />
      <mesh geometry={nodes.ZU_OMG_Chair008.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair008_1.geometry} material={materials['Chair fabric 02']} />
      <mesh geometry={nodes.ZU_OMG_Chair005.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair005_1.geometry} material={materials['Chair fabric 02']} />
      <mesh geometry={nodes.ZU_OMG_Chair001.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair001_1.geometry} material={materials['Chair fabric 01']} />
      <mesh geometry={nodes.Mesh007.geometry} material={materials['Glass stove']} />
      <mesh geometry={nodes.Mesh007_1.geometry} material={materials['Stove black']} />
      <mesh geometry={nodes.Mesh007_2.geometry} material={materials['Stove glass']} />
      <mesh geometry={nodes.Mesh007_3.geometry} material={materials.Fire} />
      <mesh geometry={nodes.NurbsPath001.geometry} material={materials.Clay} />
      <mesh geometry={nodes.NurbsPath001_1.geometry} material={materials.Soil} />
      <mesh geometry={nodes.NurbsPath001_2.geometry} material={materials['Wood plant']} />
      <mesh geometry={nodes.NurbsPath001_3.geometry} material={materials.Stalk_01} />
      <mesh geometry={nodes.NurbsPath001_4.geometry} material={materials.Leaf_01} />
      <mesh geometry={nodes.NurbsPath001_5.geometry} material={materials.Leaf_02} />
      <mesh geometry={nodes.NurbsPath001_6.geometry} material={materials.Leaf_03} />
      <mesh geometry={nodes.plant004.geometry} material={materials.Leaves} />
      <mesh geometry={nodes.plant004_1.geometry} material={materials.Band} />
      <mesh geometry={nodes.plant004_2.geometry} material={materials.Soil} />
      <mesh geometry={nodes.plant004_3.geometry} material={materials.Stalk_02} />
      <mesh geometry={nodes.plant004_4.geometry} material={materials['Wood plant']} />
      <mesh geometry={nodes.frame_IKEA.geometry} material={materials['Frame gold']} />
      <mesh geometry={nodes.frame_IKEA_1.geometry} material={materials['Painting 04']} />
      <mesh geometry={nodes.frame_IKEA_2.geometry} material={materials['passe-partout']} />
      <mesh geometry={nodes.frame_IKEA001.geometry} material={materials['Frame gold']} />
      <mesh geometry={nodes.frame_IKEA001_1.geometry} material={materials['Painting 04']} />
      <mesh geometry={nodes.frame_IKEA001_2.geometry} material={materials['passe-partout']} />
      <mesh geometry={nodes.frame_IKEA002.geometry} material={materials['Frame gold']} />
      <mesh geometry={nodes.frame_IKEA002_1.geometry} material={materials['Painting 04']} />
      <mesh geometry={nodes.frame_IKEA002_2.geometry} material={materials['passe-partout']} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Copper} />
      <mesh geometry={nodes.Sphere_1.geometry} material={materials['White Ball']} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Computer screen']} />
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Computer logo']} />
      <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Computer aluminum']} />
      <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Computer keyboard']} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['Book cover_01']} />
      <mesh geometry={nodes.Cube077_1.geometry} material={materials['Book cover_02']} />
      <mesh geometry={nodes.Cube077_2.geometry} material={materials['Books pages']} />
      <mesh geometry={nodes.Cube165.geometry} material={materials['Book cover_01']} />
      <mesh geometry={nodes.Cube165_1.geometry} material={materials['Book cover_02']} />
      <mesh geometry={nodes.Cube165_2.geometry} material={materials['Books pages']} />
      <mesh geometry={nodes.Cube149.geometry} material={materials['Book cover_01']} />
      <mesh geometry={nodes.Cube149_1.geometry} material={materials['Book cover_02']} />
      <mesh geometry={nodes.Cube149_2.geometry} material={materials['Books pages']} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Book cover_01']} />
      <mesh geometry={nodes.Cube002_1.geometry} material={materials['Book cover_02']} />
      <mesh geometry={nodes.Cube002_2.geometry} material={materials['Books pages']} />
    </group>
  )
}

useGLTF.preload('/test.gltf')
