/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hero-scene.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hero-scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[1.14, 0.74, 1.9]} rotation={[3.13, 0.02, -3.14]} scale={0.04}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube003.geometry} material={materials.aluminium} />
          <mesh geometry={nodes.Cube003_1.geometry} material={materials['matte.001']} />
          <mesh geometry={nodes.Cube003_2.geometry} material={materials['screen.001']} />
        </group>
      </group>
      <group position={[1.66, 0.73, 1.96]} rotation={[0, -0.3, 0]}>
        <mesh geometry={nodes.Tip_Table_Lamp.geometry} material={materials.Lamp_01} />
        <mesh geometry={nodes.Tip_Table_Lamp_1.geometry} material={materials['Lamp light']} />
      </group>
      <group position={[1.29, 0, 0.92]} rotation={[Math.PI / 2, 0, 0.07]} scale={0.01}>
        <mesh geometry={nodes.ZU_OMG_Chair010.geometry} material={materials['Black legs']} />
        <mesh geometry={nodes.ZU_OMG_Chair010_1.geometry} material={materials['Chair fabric 02']} />
      </group>
      <group position={[1.23, 0, 1.79]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes['Vitra_Compas_Direction_mat(1)_1'].geometry} material={materials.Vitra_Compas_Direction_mat1_mtl_3} />
        <mesh geometry={nodes['Vitra_Compas_Direction_mat(1)_2'].geometry} material={materials.Vitra_Compas_Direction_mat1_mtl_1} />
        <mesh geometry={nodes['Vitra_Compas_Direction_mat(1)_3'].geometry} material={materials.Vitra_Compas_Direction_mat1_mtl_2} />
      </group>
      <group position={[1.44, 0.73, 1.97]} rotation={[-2.96, -0.15, -1.48]} scale={[0.01, 0, 0]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials['Yellow.006']} />
      </group>
      <group position={[1.43, 0.73, 1.97]} rotation={[-3.02, -0.16, -1.67]} scale={[0.01, 0, 0]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials['light green']} />
      </group>
      <group position={[1.44, 0.74, 1.99]} rotation={[-Math.PI, -0.23, -Math.PI / 2]} scale={0.01}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['light blue']} />
      </group>
      <group position={[1.45, 0.74, 1.99]} rotation={[3.13, -0.24, -1.55]} scale={0.01}>
        <mesh geometry={nodes.Cube016.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials.blue} />
      </group>
      <group position={[1.45, 0.74, 1.99]} rotation={[-3.11, -0.18, -1.6]} scale={0.01}>
        <mesh geometry={nodes.Cube017.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials['light green']} />
      </group>
      <group position={[1.42, 0.73, 2]} rotation={[-3.07, -0.14, -1.6]} scale={0.01}>
        <mesh geometry={nodes.Cube018.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials['Yellow.006']} />
      </group>
      <group position={[1.41, 0.73, 1.99]} rotation={[-3.11, -0.2, -1.68]} scale={0.01}>
        <mesh geometry={nodes.Cube019.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.Red} />
      </group>
      <group position={[1.44, 0.74, 2]} rotation={[-3.12, -0.16, -1.6]} scale={0.01}>
        <mesh geometry={nodes.Cube020.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['light brown']} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials.pink} />
      </group>
      <mesh geometry={nodes['pen-case'].geometry} material={materials['Material.007']} position={[1.44, 0.73, 1.99]} rotation={[-Math.PI, 0.51, -Math.PI]} scale={[0.01, 0.03, 0.01]} />
      <group position={[1.46, 0.74, 1.97]} rotation={[3.01, 0.41, 2.33]} scale={[0.01, 0, 0.01]}>
        <mesh geometry={nodes.Cube021.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes['book-cover'].geometry} material={materials['Material #7.001']} position={[0.83, 0.76, 1.76]} rotation={[Math.PI, 0.33, -3.13]} scale={0} />
      <mesh geometry={nodes['book-paper'].geometry} material={materials['Material #7.001']} position={[0.83, 0.66, 1.76]} rotation={[Math.PI, 0.33, -3.13]} scale={0} />
      <mesh geometry={nodes['book-lid'].geometry} material={materials['Material #7.001']} position={[0.83, 0.73, 1.76]} rotation={[Math.PI, 0.33, 0.01]} scale={0} />
      <mesh geometry={nodes['pen-cap'].geometry} material={materials['Material #7.001']} position={[0.83, 0.76, 1.84]} rotation={[-1.63, 0.38, -2.99]} scale={0} />
      <mesh geometry={nodes['pen-joint'].geometry} material={materials['Material #7.001']} position={[0.81, 0.76, 1.69]} rotation={[-1.63, 0.38, -2.99]} scale={0} />
      <mesh geometry={nodes['pen-holder'].geometry} material={materials['Material #7.001']} position={[0.83, 0.76, 1.8]} rotation={[-3.11, -0.23, -1.19]} scale={0} />
      <mesh geometry={nodes['pen-tip'].geometry} material={materials['Material #7.001']} position={[0.81, 0.76, 1.69]} rotation={[1.52, -0.36, -0.15]} scale={0} />
      <mesh geometry={nodes['pen-handle-low'].geometry} material={materials['Material #7.001']} position={[0.81, 0.76, 1.69]} rotation={[-1.88, 1.13, -2.8]} scale={0} />
      <mesh geometry={nodes['pen-handle-top'].geometry} material={materials['Material #7.001']} position={[0.81, 0.76, 1.69]} rotation={[1.25, -1.14, -0.35]} scale={0} />
      <mesh geometry={nodes.Table.geometry} material={materials.Table} position={[-0.94, 0, 4.83]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <group position={[-1.02, 1.96, 4.83]}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials['Lamp black']} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials['Lamp white']} />
        <mesh geometry={nodes.Mesh004_2.geometry} material={materials['Lamp light table']} />
      </group>
      <group position={[1.55, 2.08, 2.08]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.57}>
        <mesh geometry={nodes.frame_IKEA005.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA005_1.geometry} material={materials.Picture_04} />
        <mesh geometry={nodes.frame_IKEA005_2.geometry} material={materials['passe-partout']} />
      </group>
      <group position={[0.9, 1.93, 2.07]} rotation={[-Math.PI / 2, 0, 0]} scale={0.76}>
        <mesh geometry={nodes.frame_IKEA004.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA004_1.geometry} material={materials.Picture_02} />
        <mesh geometry={nodes.frame_IKEA004_2.geometry} material={materials['passe-partout']} />
      </group>
      <group position={[1.53, 1.61, 2.08]} rotation={[-Math.PI / 2, 0, 0]} scale={0.4}>
        <mesh geometry={nodes.frame_IKEA003.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA003_1.geometry} material={materials.Picture_02} />
        <mesh geometry={nodes.frame_IKEA003_2.geometry} material={materials['passe-partout']} />
      </group>
      <group position={[1.52, 1.21, 2.08]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.4}>
        <mesh geometry={nodes.frame_IKEA006.geometry} material={materials['Frame black']} />
        <mesh geometry={nodes.frame_IKEA006_1.geometry} material={materials.Picture_03} />
        <mesh geometry={nodes.frame_IKEA006_2.geometry} material={materials['passe-partout']} />
      </group>
      <group position={[1.14, 0.74, 1.78]} rotation={[-Math.PI, 0.02, -Math.PI]} scale={0.04}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.aluminium} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.trackpad} />
      </group>
      <mesh geometry={nodes.keyboard.geometry} material={materials.keys} position={[1.07, 0.74, 1.77]} rotation={[-Math.PI, 0.02, -Math.PI]} scale={0.04} />
      <mesh geometry={nodes.touchbar.geometry} material={materials.touchbar} position={[1.14, 0.74, 1.87]} rotation={[-Math.PI, 0.02, -Math.PI]} scale={0.04} />
      <group position={[0.77, 0.73, 1.97]} rotation={[Math.PI / 2, 0, -3.13]} scale={0}>
        <mesh geometry={nodes.Untitled052.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Untitled052_1.geometry} material={materials.cap} />
        <mesh geometry={nodes.Untitled052_2.geometry} material={materials['default.012']} />
      </group>
      <group position={[0.73, 0.73, 1.96]} rotation={[Math.PI / 2, 0, -0.91]} scale={0}>
        <mesh geometry={nodes.Untitled072.geometry} material={materials['default.013']} />
        <mesh geometry={nodes.Untitled072_1.geometry} material={materials['default.014']} />
        <mesh geometry={nodes.Untitled072_2.geometry} material={materials['default.015']} />
      </group>
      <group position={[0.83, 0.73, 1.99]} rotation={[Math.PI / 2, 0, 3.07]} scale={0}>
        <mesh geometry={nodes.Untitled064.geometry} material={materials['default.006']} />
        <mesh geometry={nodes.Untitled064_1.geometry} material={materials['default.007']} />
        <mesh geometry={nodes.Untitled064_2.geometry} material={nodes.Untitled064_2.material} />
        <mesh geometry={nodes.Untitled064_3.geometry} material={nodes.Untitled064_3.material} />
      </group>
      <group position={[0.7, 0.73, 1.95]} rotation={[Math.PI / 2, 0, 2.91]} scale={0}>
        <mesh geometry={nodes.Untitled007.geometry} material={materials['default.016']} />
        <mesh geometry={nodes.Untitled007_1.geometry} material={materials['default.017']} />
        <mesh geometry={nodes.Untitled007_2.geometry} material={materials['default.018']} />
      </group>
      <group position={[0.9, 0.73, 1.99]} rotation={[Math.PI / 2, 0, -3.1]} scale={0}>
        <mesh geometry={nodes.Untitled078.geometry} material={materials['default']} />
        <mesh geometry={nodes.Untitled078_1.geometry} material={materials['default.001']} />
        <mesh geometry={nodes.Untitled078_2.geometry} material={materials['default.002']} />
      </group>
      <group position={[0.95, 0.73, 2]} rotation={[Math.PI / 2, 0, -2.98]} scale={0}>
        <mesh geometry={nodes.Untitled018.geometry} material={materials['default.003']} />
        <mesh geometry={nodes.Untitled018_1.geometry} material={materials['default.004']} />
        <mesh geometry={nodes.Untitled018_2.geometry} material={materials['default.005']} />
      </group>
      <mesh geometry={nodes.tablet.geometry} material={materials['Material.002']} position={[1.63, 0.74, 1.74]} rotation={[Math.PI, -0.17, Math.PI]} scale={0.9} />
      <group position={[1.7, 0.74, 1.76]} rotation={[-1.67, 1.08, 0.12]} scale={0}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[1.47, 0.74, 1.78]} rotation={[-Math.PI / 2, 0, -2.95]} scale={0.09}>
        <mesh geometry={nodes.Plane.geometry} material={materials.metal} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['matte black']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.glass} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials.black} />
        <mesh geometry={nodes.Plane_5.geometry} material={materials['glass type 2']} />
        <group position={[0.72, 0.99, -0.06]} rotation={[1.58, 0, 0]}>
          <mesh geometry={nodes.Plane002.geometry} material={materials.metal} />
          <mesh geometry={nodes.Plane002_1.geometry} material={materials.glass} />
          <mesh geometry={nodes.Plane002_2.geometry} material={materials['matte black']} />
        </group>
        <group position={[0.77, 0.94, -0.06]} rotation={[1.58, 0, 0]}>
          <mesh geometry={nodes.Circle002.geometry} material={materials['matte black']} />
          <mesh geometry={nodes.Circle002_1.geometry} material={materials.glass} />
          <mesh geometry={nodes.Circle002_2.geometry} material={materials.lens} />
          <mesh geometry={nodes.Circle002_3.geometry} material={materials['metal for cams']} />
          <mesh geometry={nodes.Circle002_4.geometry} material={materials.lidar} />
          <mesh geometry={nodes.Circle002_5.geometry} material={materials.flash} />
          <mesh geometry={nodes.Circle002_6.geometry} material={materials['flash ']} />
        </group>
        <mesh geometry={nodes.Logo.geometry} material={materials['metal.001']} position={[0, -0.01, -0.05]} rotation={[-3.13, 0, -Math.PI]} />
      </group>
      <mesh geometry={nodes.Door_frame.geometry} material={materials.White_Door} position={[-1.48, 1.23, 2.14]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.Base.geometry} material={materials.Base} position={[-2.04, 0.14, -0.88]} />
      <group position={[0, 1.7, 0]} scale={[1.58, 1, 1.58]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Ceiling} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Base} />
      </group>
      <mesh geometry={nodes.Walls_inside.geometry} material={materials['Wall plaster']} position={[-0.81, 2.08, -1.89]} />
      <mesh geometry={nodes.Window_sill.geometry} material={materials['Marble 01']} position={[0, 1.5, 0]} scale={[1.58, 1, 1.58]} />
      <group position={[0, 0, 4.9]}>
        <mesh geometry={nodes.Mesh019.geometry} material={materials.Copper} />
        <mesh geometry={nodes.Mesh019_1.geometry} material={materials['White window']} />
      </group>
      <mesh geometry={nodes.ZU_OMG_Chair001.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair001_1.geometry} material={materials['Chair fabric 01']} />
      <mesh geometry={nodes.ZU_OMG_Chair004.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair004_1.geometry} material={materials['Chair fabric 01']} />
      <mesh geometry={nodes.ZU_OMG_Chair003.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair003_1.geometry} material={materials['Chair fabric 01']} />
      <mesh geometry={nodes.ZU_OMG_Chair005.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair005_1.geometry} material={materials['Chair fabric 02']} />
      <mesh geometry={nodes.ZU_OMG_Chair008.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair008_1.geometry} material={materials['Chair fabric 02']} />
      <mesh geometry={nodes.ZU_OMG_Chair002.geometry} material={materials['Black legs']} />
      <mesh geometry={nodes.ZU_OMG_Chair002_1.geometry} material={materials['Chair fabric 02']} />
      <mesh geometry={nodes.frame_IKEA001.geometry} material={materials['Frame gold']} />
      <mesh geometry={nodes.frame_IKEA001_1.geometry} material={materials['Painting 04']} />
      <mesh geometry={nodes.frame_IKEA001_2.geometry} material={materials['passe-partout']} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Cube008_1.geometry} material={materials['Balcony floor']} />
    </group>
  )
}

useGLTF.preload('/hero-scene.gltf')
